#!/usr/bin/env python3
"""Regenerate tools/localfuzz/loop_keywords.py from vani-compiler's own
src/lexer.rs -- the single source of truth for every dialect's keyword
spellings.

Why this exists: harness.py's mutator has three places that need to
recognize a `while`/`for ... from ... to/downto`/`fn`/`let` statement by
looking at the line's *text* (no real vani parser in the loop -- these
are cheap, line-level text mutators). All three originally checked only
the literal English spellings ("while ", "for ", " from ", " to ",
" downto ", "fn ", "let "), which silently does nothing on every one of
this corpus's ~60 translated-dialect example files (Russian "пока",
Punjabi Shahmukhi "فنکشن", Mongolian "ᠴᠠᠭ", ...) since only English-
dialect files ever contain those literal words. Found while triaging
the digest's dominant [166x]/[8x]/[3x] run-crash clusters (LLVM/lli
interpreter timeout, sometimes with a clean C-side assertion failure) --
a Russian control-flow repro's `пока i < 9223372036854775807 { ... }`
(a mutated i64::MAX loop bound landing in a *translated* while-loop,
completely invisible to the English-only `_is_slow_prone_position`
check that exists specifically to steer i64::MIN/MAX literals away from
loop bounds and sleep_ms args) confirmed this is a real, live gap, not
just a theoretical one -- and it plausibly explains a large fraction of
the digest's timeout-shaped findings, since most corpus files are
non-English.

Same "hand-copied table silently drifts from the real source" shape
vani-compiler's own tools/regen_vani_translate_keywords.py already
documents for BUG-173 (src/lsp.rs) and vani_translate.py's ALIASES --
extracting mechanically from lexer.rs here for the same reason: this
table should never be hand-typed or hand-extended per dialect.

Usage:
    python3 tools/localfuzz/regen_loop_keywords.py [path-to-vani-compiler]

Defaults to ../vani-compiler relative to this localfuzz checkout if no
path is given (matches this project's own established sibling-checkout
layout).
"""
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT_PATH = HERE / "loop_keywords.py"


def extract(lexer_src: str, token_kinds: list[str]) -> list[str]:
    pattern = re.compile(
        r'"((?:[^"\\]|\\.)+)"\s*=>\s*TokenKind::(?:' + "|".join(token_kinds) + r")\b"
    )
    words = set()
    for m in pattern.finditer(lexer_src):
        words.add(m.group(1))
    return sorted(words)


def main() -> int:
    if len(sys.argv) > 1:
        compiler_root = Path(sys.argv[1]).resolve()
    else:
        compiler_root = (HERE / ".." / ".." / ".." / "vani-compiler").resolve()
    lexer_path = compiler_root / "src" / "lexer.rs"
    if not lexer_path.exists():
        print(f"error: {lexer_path} not found -- pass the vani-compiler "
              f"checkout path explicitly", file=sys.stderr)
        return 1

    lexer_src = lexer_path.read_text()

    loop_words = extract(lexer_src, ["While", "For", "From", "To", "DownTo"])
    fn_words = extract(lexer_src, ["Fn"])
    let_words = extract(lexer_src, ["Let"])

    if not loop_words or not fn_words or not let_words:
        print("error: extraction found zero keywords -- lexer.rs's match-arm "
              "shape may have changed; check the regex above before trusting "
              "an empty table", file=sys.stderr)
        return 1

    lines = [
        '"""Generated by regen_loop_keywords.py from vani-compiler\'s own',
        "src/lexer.rs -- every dialect's spelling of the keywords harness.py's",
        "line-level text mutators need to recognize across all ~60 example",
        "languages, not just English. Do not hand-edit; re-run the",
        "generator instead (see that script's own docstring for why).",
        '"""',
        "",
        f"# {len(loop_words)} distinct spellings across every dialect's While/",
        "# For/From/To/DownTo keywords.",
        "LOOP_KEYWORDS = " + repr(loop_words) + "",
        "",
        f"# {len(fn_words)} distinct spellings across every dialect's Fn keyword.",
        "FN_KEYWORDS = " + repr(fn_words) + "",
        "",
        f"# {len(let_words)} distinct spellings across every dialect's Let keyword.",
        "LET_KEYWORDS = " + repr(let_words) + "",
        "",
    ]
    OUT_PATH.write_text("\n".join(lines))
    print(f"Wrote {OUT_PATH} -- {len(loop_words)} loop keyword(s), "
          f"{len(fn_words)} fn keyword(s), {len(let_words)} let keyword(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
